# Generated by Django 4.2.4 on 2023-12-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=400, null=True)),
                ('experence', models.CharField(max_length=30, null=True)),
                ('schedule', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('quentity', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=40, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('not_received', models.BooleanField(default=False)),
                ('chat_id', models.CharField(max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.region')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.services')),
            ],
        ),
    ]
